function plotObjects( ObjectPositions,dimension )
%plotObjects display objects positions in matlab
hold on

for i=1:size(ObjectPositions,1)
    if(dimension==3)
    plot3(ObjectPositions(i,1),...
        ObjectPositions(i,2),...
        2.0,...
        's',...
        'MarkerSize',15,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor',[1.0,1.0,1.0])
    else
        plot(ObjectPositions(i,1),...
        ObjectPositions(i,2),...
        's',...
        'MarkerSize',15,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor',[1.0,1.0,1.0])    
    end
end
end

