function Mat2Cmatrix( M )
%Mat2Cmatrix This function takes a Matlab matrix
%and writes a text file for a C++ matrix, this is useful when deriving complex  symbolic matrix  
% using MUPAD and instead of rewriting labriously
% we can use this function

[nrows, ncols]=size(M);
file_1 = fopen('Mat.txt','w') ;

fprintf(file_1,'/*------------------------------------------------------ \n Matrix Generated by function Mat2Cmatrix \n------------------------------------------------------ */ \n \n') ; 
for i=1:nrows
    for j=1:ncols
    ElementofM=all2str(M(i,j));     
    indexi=int2str((i-1));
    indexj=int2str((j-1));
    S=strcat('M[',indexi,'][',indexj,']=',ElementofM,';');
    fprintf(file_1,S); 
    fprintf(file_1,'\n');
    end
end

% Copyright (c) 2012 Philip Long
%
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, subject to the following conditions:
%
% The above copyright notice and this permission notice shall be included in
% all copies or substantial portions of the Software.
%
% The Software is provided "as is", without warranty of any kind.